VBoxManage startvm vs001 --type headless 
VBoxManage startvm vs002 --type headless 
VBoxManage startvm vs003 --type headless 
VBoxManage startvm vs004 --type headless 
VBoxManage startvm vs005 --type headless 
VBoxManage startvm vs006 --type headless 
VBoxManage startvm vs007 --type headless 
VBoxManage startvm vs008 --type headless 
VBoxManage startvm vs009 --type headless 
VBoxManage startvm vs010 --type headless 
VBoxManage startvm vs011 --type headless 
VBoxManage startvm vs012 --type headless 
VBoxManage startvm vs013 --type headless 
VBoxManage startvm vs014 --type headless 
VBoxManage startvm vs015 --type headless 
